import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { ArrowRight, BookOpen, Check, ChevronDown, ChevronUp, Clock3, Download, FileJson, FileText, Filter, GitFork, Lightbulb, RotateCcw, ShieldCheck, Sparkles, TriangleAlert, Users } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { Link } from "react-router-dom";
import { api, isMockMode } from "../../api/api-provider";
import { geographyLabels, modeLabels, sourceTypeLabels } from "../../domain/labels";
import type { AnalysisMode, Geography, ParsedQuery, QueryFilters, ResearchAnswer } from "../../domain/types";
import { useSession } from "../../app/session-context";
import { Badge, Stars } from "../../components/ui/Primitives";
import { downloadJsonLd, downloadMarkdown, downloadPdf } from "../export/export";
import s from "../../styles/ui.module.css";

const examples = [
  { label: "Обессоливание воды", query: "Какие методы обессоливания воды подходят, если сульфаты и хлориды составляют 200–300 мг/л, а сухой остаток должен быть ≤1000 мг/л?" },
  { label: "Циркуляция католита", query: "Какие решения циркуляции католита при электроэкстракции никеля применяются в мировой практике и какая скорость считается оптимальной?" },
  { label: "Au, Ag и МПГ", query: "Покажите эксперименты и публикации по распределению Au, Ag и МПГ между штейном и шлаком за последние 5 лет" },
  { label: "Шахтные воды", query: "Сравните российские и зарубежные способы закачки шахтных вод в глубокие горизонты и их технико-экономические показатели" },
];
const stages = ["Разбираем условия запроса", "Ищем релевантные источники", "Обходим граф знаний", "Проверяем числа и единицы", "Формируем аналитический вывод"];

export function SearchPage() {
  const [query, setQuery] = useState(""); const [mode, setMode] = useState<AnalysisMode | "auto">("auto");
  const [parsed, setParsed] = useState<ParsedQuery | null>(null); const [stage, setStage] = useState(0); const [filtersOpen, setFiltersOpen] = useState(false); const [hiddenTokens, setHiddenTokens] = useState<Set<string>>(new Set());
  const [filters, setFilters] = useState<QueryFilters>({ trustMin: 3 }); const [answer, setAnswer] = useState<ResearchAnswer | null>(null);
  const { history, refreshHistory } = useSession(); const resultRef = useRef<HTMLDivElement>(null);
  const ask = useMutation<ResearchAnswer, Error, { query: string; mode: AnalysisMode | "auto"; filters: QueryFilters }>({ mutationFn: (request) => api.ask(request), onSuccess(result) { setAnswer(result); refreshHistory(); window.setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 80); } });
  useEffect(() => { setHiddenTokens(new Set()); if (query.trim().length < 5) { setParsed(null); return; } const timer = window.setTimeout(() => api.parseQuery(query).then(setParsed), 280); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { if (!ask.isPending) { setStage(0); return; } const timer = window.setInterval(() => setStage((value) => Math.min(value + 1, stages.length - 1)), 350); return () => window.clearInterval(timer); }, [ask.isPending]);
  const tokens = useMemo(() => (parsed ? [...parsed.materials, ...parsed.processes, ...parsed.geography.map((g) => ({ id: `geo-${g}`, label: geographyLabels[g], value: g })), ...parsed.conditions.map((c) => ({ id: c.id, label: `${c.parameter}: ${c.operator} ${c.value}${c.valueTo ? `–${c.valueTo}` : ""} ${c.unit}`, value: c.id })), ...(parsed.yearRange ? [{ id: "years", label: `${parsed.yearRange[0]}–${parsed.yearRange[1]}`, value: "years" }] : [])] : []).filter((token) => !hiddenTokens.has(token.id)), [parsed, hiddenTokens]);
  function submit(nextQuery = query) { if (!nextQuery.trim()) return; setQuery(nextQuery); setAnswer(null); ask.mutate({ query: nextQuery, mode, filters }); }
  return <div className={s.searchPage}>
    <section className={`${s.hero} ${answer ? s.heroCompact : ""}`}>
      <div className={s.heroIntro}>{isMockMode && <Badge tone="blue"><Sparkles size={13}/> Автономное демо</Badge>}<h1>Знания R&D — в одном ответе</h1><p>Задайте вопрос о материалах, процессах и условиях. Система найдёт связи, проверит числа и покажет доказательства.</p></div>
      <div className={s.queryCard}>
        <div className={s.modeTabs} aria-label="Режим анализа">{(["auto", "answer", "literature_review", "comparison"] as const).map((item) => <button key={item} className={mode === item ? s.modeActive : ""} onClick={() => setMode(item)}>{modeLabels[item]}{item === "auto" && parsed && <small>{modeLabels[parsed.intent]}</small>}</button>)}</div>
        <div className={s.queryInputWrap}><textarea value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") submit(); }} placeholder="Например: сравните способы циркуляции католита при электроэкстракции никеля…" rows={answer ? 2 : 3}/><button className={s.primaryButton} disabled={!query.trim() || ask.isPending} onClick={() => submit()}>{ask.isPending ? "Анализируем" : "Исследовать"}<ArrowRight size={18}/></button></div>
        {tokens.length > 0 && <div className={s.parsedRow}><span><Sparkles size={15}/>Распознано:</span><div className={s.tokenList}>{tokens.map((token) => <button key={token.id} className={s.token} aria-label={`Удалить фильтр ${token.label}`} onClick={() => setHiddenTokens((current) => new Set(current).add(token.id))}>{token.label}<span>×</span></button>)}</div></div>}
        <div className={s.queryFooter}><button className={s.textButton} onClick={() => setFiltersOpen((value) => !value)}><Filter size={16}/>Фильтры{filtersOpen ? <ChevronUp size={15}/> : <ChevronDown size={15}/>}</button><span>Ctrl + Enter</span></div>
        {filtersOpen && <div className={s.filterPanel}><label>География<select value={filters.geography?.[0] ?? ""} onChange={(e) => setFilters((f) => ({ ...f, geography: e.target.value ? [e.target.value as Geography] : undefined }))}><option value="">Любая</option><option value="Russia">Россия</option><option value="Foreign">Зарубежная</option><option value="Global">Глобальная</option></select></label><label>Год от<input type="number" value={filters.yearFrom ?? ""} onChange={(e) => setFilters((f) => ({ ...f, yearFrom: e.target.value ? Number(e.target.value) : undefined }))}/></label><label>Доверие<select value={filters.trustMin ?? 1} onChange={(e) => setFilters((f) => ({ ...f, trustMin: Number(e.target.value) }))}><option value="1">Любое</option><option value="3">От 3 звёзд</option><option value="4">От 4 звёзд</option><option value="5">Только 5 звёзд</option></select></label></div>}
      </div>
      {!answer && !ask.isPending && <><div className={s.exampleRow}>{examples.map((example) => <button key={example.label} onClick={() => { setQuery(example.query); submit(example.query); }}><span>{example.label}</span><ArrowRight size={15}/></button>)}</div>{history.length > 0 && <div className={s.history}><Clock3 size={16}/><span>Недавние:</span>{history.slice(0, 3).map((item) => <button key={item} onClick={() => setQuery(item)}>{item}</button>)}</div>}</>}
    </section>
    {ask.isPending && <Processing stage={stage}/>} {ask.isError && <div className={s.errorBanner}><TriangleAlert/>Ошибка анализа: {ask.error.message}<button onClick={() => submit()}><RotateCcw size={16}/>Повторить</button></div>}
    {answer && <div ref={resultRef}><AnswerView answer={answer}/></div>}
  </div>;
}

function Processing({ stage }: { stage: number }) { return <section className={s.processing} aria-live="polite"><div className={s.processingOrb}><Sparkles/></div><div><h2>{stages[stage]}</h2><p>Сопоставляем запрос с документами и графом знаний</p><div className={s.progressTrack}><span style={{ width: `${((stage + 1) / stages.length) * 100}%` }}/></div><div className={s.stageList}>{stages.map((label, index) => <span key={label} className={index <= stage ? s.stageDone : ""}>{index < stage ? <Check size={13}/> : index + 1}{label}</span>)}</div></div></section>; }

function AnswerView({ answer }: { answer: ResearchAnswer }) {
  const [openSources, setOpenSources] = useState<Set<string>>(new Set([answer.sources[0]?.id]));
  return <article className={s.answerView}>
    <header className={s.answerHeader}><div><div className={s.eyebrow}>АНАЛИТИЧЕСКАЯ ЗАПИСКА</div><h2>Результат исследования</h2><div className={s.answerMeta}><span><Clock3/> {(answer.processing.durationMs / 1000).toFixed(1)} сек</span><span><BookOpen/> {answer.sources.length} источника</span><span><GitFork/> {answer.processing.graphNodesVisited} узлов проверено</span></div></div><div className={s.exportGroup}><button onClick={() => downloadMarkdown(answer)} title="Markdown"><FileText/>MD</button><button onClick={() => downloadJsonLd(answer)} title="JSON-LD"><FileJson/>JSON-LD</button><button onClick={() => void downloadPdf(answer)} title="PDF"><Download/>PDF</button></div></header>
    <div className={s.answerGrid}><div className={s.answerMain}>
      <section className={`${s.panel} ${s.summaryPanel}`}><div className={s.panelIcon}><Lightbulb/></div><div><h3>Главный вывод</h3><ReactMarkdown>{answer.summary}</ReactMarkdown></div></section>
      {answer.numericParameters.length > 0 && <section className={s.panel}><SectionTitle icon={<ShieldCheck/>} title="Ключевые параметры" subtitle="Значения привязаны к источникам и условиям"/><div className={s.parameterGrid}>{answer.numericParameters.map((parameter) => <div key={parameter.id} className={s.parameterCard}><span>{parameter.label}</span><strong>{parameter.value} <small>{parameter.unit}</small></strong><Badge tone={parameter.applicability === "matches" ? "green" : parameter.applicability === "outside" ? "red" : "amber"}>{parameter.applicability === "matches" ? "Соответствует" : parameter.applicability === "outside" ? "Вне условия" : "Зависит от условий"}</Badge></div>)}</div></section>}
      <section className={s.panel}><SectionTitle icon={<FileText/>} title="Что установлено" subtitle="Выводы с оценкой применимости"/><div className={s.findingList}>{answer.findings.map((finding) => <div key={finding.id} className={s.finding}><span className={`${s.findingStatus} ${s[`finding_${finding.status}`]}`}>{finding.status === "supported" ? <Check/> : finding.status === "conditional" ? <TriangleAlert/> : <CircleHelpIcon/>}</span><div><h4>{finding.title}</h4><p>{finding.text}</p><small>{finding.sourceIds.map((id) => `[${answer.sources.findIndex((source) => source.id === id) + 1}]`).join(" ")}</small></div></div>)}</div></section>
      {answer.comparisons.length > 0 && <section className={s.panel}><SectionTitle icon={<GitFork/>} title="Сравнение решений" subtitle="Параметры и ограничения вариантов"/><div className={s.comparisonTable}><div className={s.tableHead}><span>Решение</span><span>Параметры</span><span>Сильные стороны</span><span>Ограничения</span></div>{answer.comparisons.map((row) => <div className={s.tableRow} key={row.id}><span data-label="Решение"><b>{row.method}</b><small>{row.geography}</small></span><span data-label="Параметры">{row.parameters}</span><span data-label="Сильные стороны">{row.strengths}</span><span data-label="Ограничения">{row.limitations}</span></div>)}</div></section>}
      {answer.validations.length > 0 && <section className={s.validationPanel}><Check/><div><h3>Подтверждено несколькими источниками</h3>{answer.validations.map((item) => <p key={item.id}>{item.statement}</p>)}</div></section>}
      {answer.contradictions.length > 0 && <section className={s.contradictionPanel}><SectionTitle icon={<TriangleAlert/>} title="Расхождения и ограничения" subtitle="Сравниваем только сопоставимые условия"/>{answer.contradictions.map((item) => <div key={item.id} className={s.contradictionItem}><h4>{item.parameter}</h4><p>{item.context}</p><div>{item.values.map((value) => <span key={value.sourceId}><b>{value.value}</b><small>{value.conditions}</small></span>)}</div><em>{item.explanation}</em></div>)}</section>}
      <section className={s.panel}><SectionTitle icon={<BookOpen/>} title={`Источники · ${answer.sources.length}`} subtitle="Откройте доказательный фрагмент"/><div className={s.sourceList}>{answer.sources.map((source, index) => { const open = openSources.has(source.id); return <div className={s.sourceCard} key={source.id}><button className={s.sourceHead} onClick={() => setOpenSources((current) => { const next = new Set(current); open ? next.delete(source.id) : next.add(source.id); return next; })}><span className={s.sourceNumber}>{index + 1}</span><span><b>{source.title}</b><small>{source.year ?? "Год не определён"} · {geographyLabels[source.geography]} · {sourceTypeLabels[source.sourceType]}</small></span><Stars value={source.trust}/>{open ? <ChevronUp/> : <ChevronDown/>}</button>{open && <div className={s.sourceBody}><blockquote>«{source.quote}»</blockquote><p>{source.filename}{source.page ? ` · стр. ${source.page}` : source.section ? ` · ${source.section}` : ""}</p><code>{source.chunkId}</code></div>}</div>; })}</div></section>
      {answer.experts.length > 0 && <section className={s.panel}><SectionTitle icon={<Users/>} title="Эксперты" subtitle="Авторы и носители компетенций"/><div className={s.expertGrid}>{answer.experts.map((expert) => <div key={expert.id} className={s.expertCard}><span>{expert.name.split(" ").map((n) => n[0]).join("").slice(0, 2)}</span><div><b>{expert.name}</b><small>{expert.organization}</small><p>{expert.expertise.join(" · ")}</p></div></div>)}</div></section>}
      {answer.gaps.length > 0 && <section className={s.panel}><SectionTitle icon={<Lightbulb/>} title="Пробелы в знаниях" subtitle="Что исследовать дальше"/>{answer.gaps.map((gap) => <div key={gap.id} className={s.gapRow}><div><b>{gap.material} × {gap.process}</b><span>{gap.condition}</span></div><p>{gap.recommendation}</p></div>)}</section>}
    </div><aside className={s.answerAside}><div className={s.confidenceCard}><span>Уверенность ответа</span><strong>{answer.confidence.overall}%</strong><div className={s.confidenceRing} style={{ "--score": `${answer.confidence.overall * 3.6}deg` } as React.CSSProperties}/><b>{answer.confidence.label}</b><Confidence label="Извлечение" value={answer.confidence.extraction}/><Confidence label="Качество источников" value={answer.confidence.sourceQuality}/><Confidence label="Подтверждение" value={answer.confidence.corroboration}/></div>{answer.graphPreview.nodes.length > 0 && <div className={s.asideCard}><GitFork/><h3>Граф ответа</h3><p>{answer.graphPreview.nodes.length} сущностей, {answer.graphPreview.edges.length} связей</p><Link to="/graph">Открыть граф <ArrowRight/></Link></div>}</aside></div>
  </article>;
}
function Confidence({ label, value }: { label: string; value: number }) { return <div className={s.confidenceLine}><span>{label}<b>{value}%</b></span><i><em style={{ width: `${value}%` }}/></i></div>; }
function SectionTitle({ icon, title, subtitle }: { icon: React.ReactNode; title: string; subtitle: string }) { return <div className={s.sectionTitle}><span>{icon}</span><div><h3>{title}</h3><p>{subtitle}</p></div></div>; }
function CircleHelpIcon() { return <span>?</span>; }
