import { useQuery } from "@tanstack/react-query";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BookOpenText, CircleHelp, Database, GitFork, Network, ShieldCheck, TriangleAlert, Users } from "lucide-react";
import { api } from "../../api/api-provider";
import { ErrorState, LoadingBlock, PageHeader } from "../../components/ui/Primitives";
import s from "../../styles/ui.module.css";

const palette = ["#2563eb", "#0f766e", "#d97706", "#7c3aed", "#64748b"];
export function AnalyticsPage() {
  const result = useQuery({ queryKey: ["dashboard"], queryFn: api.getDashboard.bind(api) }); const data = result.data;
  return <div><PageHeader eyebrow="ПОКРЫТИЕ КОРПУСА" title="Аналитика" description="Масштаб базы знаний, распределение источников и зоны риска."/>
    {result.isLoading ? <LoadingBlock/> : result.isError ? <ErrorState message={result.error.message}/> : data && <><div className={s.metricGrid}><Metric icon={<BookOpenText/>} value={data.totals.documents.toLocaleString("ru-RU")} label="Документов"/><Metric icon={<Database/>} value={compact(data.totals.facts)} label="Фактов"/><Metric icon={<Network/>} value={data.totals.nodes.toLocaleString("ru-RU")} label="Узлов"/><Metric icon={<GitFork/>} value={compact(data.totals.edges)} label="Связей"/><Metric icon={<Users/>} value={data.totals.experts} label="Экспертов"/><Metric icon={<TriangleAlert/>} value={data.totals.contradictions} label="Противоречий" tone="red"/><Metric icon={<CircleHelp/>} value={data.totals.gaps} label="Пробелов" tone="amber"/><Metric icon={<ShieldCheck/>} value={`${data.totals.confidence}%`} label="Уверенность" tone="green"/></div>
      <div className={s.chartGrid}><section className={`${s.panel} ${s.chartWide}`}><ChartTitle title="Рост корпуса" subtitle="Документы по годам"/><div className={s.chart}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.byYear}><CartesianGrid stroke="#e7eaf0" vertical={false}/><XAxis dataKey="year" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="count" stroke="#2563eb" strokeWidth={3} fill="#dbe7ff"/></AreaChart></ResponsiveContainer></div></section>
      <section className={s.panel}><ChartTitle title="География" subtitle="Практики по регионам"/><div className={s.donutWrap}><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={data.byGeography} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={3}>{data.byGeography.map((_, index) => <Cell key={index} fill={palette[index % palette.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className={s.donutLegend}>{data.byGeography.map((item,index) => <span key={item.name}><i style={{background: palette[index]}}/>{item.name}<b>{item.value}</b></span>)}</div></div></section>
      <section className={s.panel}><ChartTitle title="Домены" subtitle="Доля структурированных знаний"/><div className={s.chart}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.byDomain} layout="vertical" margin={{left: 20}}><CartesianGrid stroke="#e7eaf0" horizontal={false}/><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={130} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="value" radius={[0,6,6,0]} fill="#0f766e" barSize={18}/></BarChart></ResponsiveContainer></div></section>
      <section className={s.panel}><ChartTitle title="Типы источников" subtitle="Состав документального корпуса"/><div className={s.sourceBars}>{data.bySourceType.map((item) => <div key={item.name}><span>{item.name}<b>{item.value}</b></span><i><em style={{width: `${item.value / Math.max(...data.bySourceType.map((x) => x.value)) * 100}%`}}/></i></div>)}</div></section></div>
      <div className={s.bottomAnalytics}><section className={s.panel}><ChartTitle title="Покрытие материал × процесс" subtitle="Уверенность структурированных связей"/><div className={s.coverageList}>{data.coverage.map((item) => <div key={`${item.material}-${item.process}`}><span><b>{item.material}</b><small>{item.process}</small></span><i><em style={{width:`${item.score}%`}}/></i><strong>{item.score}%</strong></div>)}</div></section><section className={s.panel}><ChartTitle title="Слабое покрытие" subtitle="Темы для следующего исследования"/><div className={s.weakList}>{data.weakTopics.map((item,index) => <div key={item.topic}><span>{index+1}</span><p>{item.topic}</p><b>{item.documents} док.</b></div>)}</div></section></div></>}
  </div>;
}
function Metric({ icon, value, label, tone = "blue" }: { icon: React.ReactNode; value: string|number; label: string; tone?: string }) { return <div className={s.metricCard}><span className={s[`metric_${tone}`]}>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>; }
function ChartTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className={s.chartTitle}><h3>{title}</h3><p>{subtitle}</p></div>; }
function compact(value: number) { return value > 999_999 ? `${(value/1_000_000).toFixed(1)} млн` : value > 999 ? `${(value/1000).toFixed(1)} тыс.` : String(value); }
